.TH "Trabalho/src/bancodados.cpp" 3 "Fri Jun 30 2017" "Version 1.0" "SOCIAL NETWORK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trabalho/src/bancodados.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'bancodados\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "lista_usuario * \fBRecupDadosUsuario\fP (lista_usuario *listaUsuario)"
.br
.RI "Funcao que dada uma lista, recupera os dados desse arquivo para a lista de usuarios\&. "
.ti -1c
.RI "ListaTransacao * \fBRecupDadosTransacoes\fP (ListaTransacao *listaTransacao)"
.br
.RI "Funcao que dada uma lista, recupera os dados desse arquivo para a lista de transacoes\&. "
.ti -1c
.RI "ListaCategoria * \fBRecupDadosCategorias\fP (ListaCategoria *listaCat)"
.br
.RI "Funcao que dada uma lista, recupera os dados desse arquivo para a lista de categorias\&. "
.ti -1c
.RI "Grafo * \fBRecupDadosGrafoAmiz\fP (Grafo *grafoAmizade)"
.br
.RI "Funcao que dado um grafo, recupera os dados desse arquivo para o grafo de amizades\&. "
.ti -1c
.RI "Grafo * \fBRecupDadosGrafoTransac\fP (Grafo *grafoTransacoes)"
.br
.RI "Funcao que dado um grafo, recupera os dados desse arquivo para o grafo de transacoes\&. "
.ti -1c
.RI "int \fBSalvaArquivoUsuario\fP (lista_usuario *listaUsuario)"
.br
.RI "Funcao que, antes do programa encerrar de fato, vai salvar todos os usuarios e suas informacoes em um arquivo\&. "
.ti -1c
.RI "int \fBSalvaArquivoTransacao\fP (ListaTransacao *listaTransacao)"
.br
.RI "Funcao que, antes do programa encerrar de fato, vai salvar todos as transacoes e suas informacoes em um arquivo\&. "
.ti -1c
.RI "int \fBSalvaArquivoCategorias\fP (ListaCategoria *listaCat)"
.br
.RI "Funcao que, antes do programa encerrar de fato, vai salvar todas as categorias e suas informacoes em um arquivo\&. "
.ti -1c
.RI "int \fBSalvaArquivoGrafoAmiz\fP (Grafo *grafoAmizade)"
.br
.RI "Funcao que, antes do programa encerrar de fato, vai salvar o grafo de amizades em um arquivo\&. "
.ti -1c
.RI "int \fBSalvaArquivoGrafoTransacao\fP (Grafo *grafoTransacoes)"
.br
.RI "Funcao que, antes do programa encerrar de fato, vai salvar o grafo de transacoes em um arquivo\&. "
.ti -1c
.RI "int \fBRecupInfosUsuaID\fP (lista_usuario *listaUsuario, ListaTransacao *listaTransacao)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ListaCategoria* RecupDadosCategorias (ListaCategoria * listaCat)"

.PP
Funcao que dada uma lista, recupera os dados desse arquivo para a lista de categorias\&. string que vai receber cada string entre os delimitadores do arquivo
.PP
contador para verificar qual elemento dos delimitadores do arquivo esta sendo verificado
.PP
string temporaria que vai receber cada linha do arquivo
.PP
descritor do arquivo 
.PP
Definition at line 120 of file bancodados\&.cpp\&.
.SS "Grafo* RecupDadosGrafoAmiz (Grafo * grafoAmizade)"

.PP
Funcao que dado um grafo, recupera os dados desse arquivo para o grafo de amizades\&. descritor do arquivo 
.PP
Definition at line 165 of file bancodados\&.cpp\&.
.SS "Grafo* RecupDadosGrafoTransac (Grafo * grafoTransacoes)"

.PP
Funcao que dado um grafo, recupera os dados desse arquivo para o grafo de transacoes\&. descritor do arquivo 
.PP
Definition at line 189 of file bancodados\&.cpp\&.
.SS "ListaTransacao* RecupDadosTransacoes (ListaTransacao * listaTransacao)"

.PP
Funcao que dada uma lista, recupera os dados desse arquivo para a lista de transacoes\&. descritor do arquivo
.PP
variavel do tipo Transacao que vai receber os dados que estao sendo recuperados do arquivo
.PP
string que vai receber cada string entre os delimitadores do arquivo
.PP
contador para verificar qual elemento dos delimitadores do arquivo esta sendo verificado
.PP
string temporaria que vai receber cada linha do arquivo 
.PP
Definition at line 55 of file bancodados\&.cpp\&.
.SS "lista_usuario* RecupDadosUsuario (lista_usuario * listaUsuario)"

.PP
Funcao que dada uma lista, recupera os dados desse arquivo para a lista de usuarios\&. descritor do arquivo
.PP
variavel do tipo Usuario que vai receber os dados que estao sendo recuperados do arquivo
.PP
string que vai receber cada string entre os delimitadores do arquivo
.PP
contador para verificar qual elemento dos delimitadores do arquivo esta sendo verificado
.PP
string temporaria que vai receber cada linha do arquivo 
.PP
Definition at line 4 of file bancodados\&.cpp\&.
.SS "int RecupInfosUsuaID (lista_usuario * listaUsuario, ListaTransacao * listaTransacao)"
Funcao que vai retornar as informacoes do usuario pelo ID dele, a partir da lista de usuarios E passar essas informacoes para a lista de transacoes O tipo usuario que vai ser retornado
.PP
vai ser o ponteiro para percorrer a lista de transacoes
.PP
Os ponteiros de no de usuario 
.PP
Definition at line 402 of file bancodados\&.cpp\&.
.SS "int SalvaArquivoCategorias (ListaCategoria * listaCat)"

.PP
Funcao que, antes do programa encerrar de fato, vai salvar todas as categorias e suas informacoes em um arquivo\&. vai ser o ponteiro para percorrer a lista de transacoes 
.PP
Definition at line 288 of file bancodados\&.cpp\&.
.SS "int SalvaArquivoGrafoAmiz (Grafo * grafoAmizade)"

.PP
Funcao que, antes do programa encerrar de fato, vai salvar o grafo de amizades em um arquivo\&. ponteiro de vertice para percorrer os vertices do grafo
.PP
ponteiro de vizinhos para percorrer os vizinhos do vertice do grafo 
.PP
Definition at line 319 of file bancodados\&.cpp\&.
.SS "int SalvaArquivoGrafoTransacao (Grafo * grafoTransacoes)"

.PP
Funcao que, antes do programa encerrar de fato, vai salvar o grafo de transacoes em um arquivo\&. ponteiro de vertice para percorrer os vertices do grafo
.PP
ponteiro de vizinhos para percorrer os vizinhos do vertice do grafo 
.PP
Definition at line 360 of file bancodados\&.cpp\&.
.SS "int SalvaArquivoTransacao (ListaTransacao * listaTransacao)"

.PP
Funcao que, antes do programa encerrar de fato, vai salvar todos as transacoes e suas informacoes em um arquivo\&. vai ser o ponteiro para percorrer a lista de transacoes 
.PP
Definition at line 246 of file bancodados\&.cpp\&.
.SS "int SalvaArquivoUsuario (lista_usuario * listaUsuario)"

.PP
Funcao que, antes do programa encerrar de fato, vai salvar todos os usuarios e suas informacoes em um arquivo\&. vai ser o ponteiro para percorrer a lista de usuarios 
.PP
Definition at line 211 of file bancodados\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOCIAL NETWORK from the source code\&.
