.TH "Trabalho/src/lista_usuario.cpp" 3 "Fri Jun 30 2017" "Version 1.0" "SOCIAL NETWORK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trabalho/src/lista_usuario.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lista_usuario\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "no_lista_usuario * \fBcriaNoUsuario\fP (Usuario usuario)"
.br
.ti -1c
.RI "lista_usuario * \fBcriarListaUsuario\fP ()"
.br
.ti -1c
.RI "void \fBaddNoListaUsuarioExistente\fP (lista_usuario *lista, no_lista_usuario *no)"
.br
.ti -1c
.RI "void \fBaddNoListaUsuarioNovo\fP (lista_usuario *lista, no_lista_usuario *no)"
.br
.ti -1c
.RI "void \fBdeletaNoListaUsuario\fP (lista_usuario *lista, no_lista_usuario *no)"
.br
.ti -1c
.RI "no_lista_usuario * \fBencontraNoUsuario\fP (no_lista_usuario *inicio, char cpf[])"
.br
.ti -1c
.RI "no_lista_usuario * \fBencontraNoUsuarioEmail\fP (no_lista_usuario *inicio, char email[])"
.br
.ti -1c
.RI "no_lista_usuario * \fBencontraNoUsuarioID\fP (no_lista_usuario *inicio, int id)"
.br
.ti -1c
.RI "int \fBLiberaListaUsuario\fP (lista_usuario *listaUsuario)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void addNoListaUsuarioExistente (lista_usuario * lista, no_lista_usuario * no)"
Adiciona nó na lista 
.PP
Definition at line 25 of file lista_usuario\&.cpp\&.
.SS "void addNoListaUsuarioNovo (lista_usuario * lista, no_lista_usuario * no)"
Adiciona nó na lista 
.PP
Definition at line 44 of file lista_usuario\&.cpp\&.
.SS "no_lista_usuario* criaNoUsuario (Usuario usuario)"
Cria nó 
.PP
Definition at line 5 of file lista_usuario\&.cpp\&.
.SS "lista_usuario* criarListaUsuario ()"
Cria lista 
.PP
Definition at line 14 of file lista_usuario\&.cpp\&.
.SS "void deletaNoListaUsuario (lista_usuario * lista, no_lista_usuario * no)"
Deleta um nó da lista encadeada
.PP
Caso o nó esteja no meio da lista
.PP
Caso o nó esteja no fim da lista
.PP
Caso o nó seja o primeiro da lista 
.PP
Definition at line 67 of file lista_usuario\&.cpp\&.
.SS "no_lista_usuario* encontraNoUsuario (no_lista_usuario * inicio, char cpf[])"
Procura vértice na lista
.PP
Primeiro vértice da lista 
.PP
Definition at line 101 of file lista_usuario\&.cpp\&.
.SS "no_lista_usuario* encontraNoUsuarioEmail (no_lista_usuario * inicio, char email[])"
Procura vértice na lista
.PP
Primeiro vértice da lista 
.PP
Definition at line 121 of file lista_usuario\&.cpp\&.
.SS "no_lista_usuario* encontraNoUsuarioID (no_lista_usuario * inicio, int id)"
Procura vértice na lista
.PP
Primeiro vértice da lista 
.PP
Definition at line 141 of file lista_usuario\&.cpp\&.
.SS "int LiberaListaUsuario (lista_usuario * listaUsuario)"
Funcao que libera a lista Retorna 0 se for liberada com sucesso e -1 se nao for 
.PP
Definition at line 163 of file lista_usuario\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOCIAL NETWORK from the source code\&.
