.TH "Trabalho/src/main.cpp" 3 "Fri Jun 30 2017" "Version 1.0" "SOCIAL NETWORK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trabalho/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'headers\&.hpp'\fP
.br
\fC#include 'Interfaces\&.hpp'\fP
.br
\fC#include 'bancodados\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
Funcao principal que ira chamar a primeira tela
.PP
Definition at line 5 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOCIAL NETWORK from the source code\&.
