.TH "Trabalho/src/Testes.cpp" 3 "Fri Jun 30 2017" "Version 1.0" "SOCIAL NETWORK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trabalho/src/Testes.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'catch\&.hpp'\fP
.br
\fC#include 'headers\&.hpp'\fP
.br
\fC#include 'lista_usuario\&.hpp'\fP
.br
\fC#include 'transacoes\&.hpp'\fP
.br
\fC#include 'grafos\&.hpp'\fP
.br
\fC#include 'categoria\&.hpp'\fP
.br
\fC#include 'bancodados\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCATCH_CONFIG_MAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_CASE\fP ('Testes da biblioteca lista_usuario\&.hpp:')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('Testes da biblioteca transacoes\&.hpp:')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('Testes da biblioteca categoria\&.hpp:')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('Testes da biblioteca bancodados\&.hpp:')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CATCH_CONFIG_MAIN"

.PP
Definition at line 1 of file Testes\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "TEST_CASE ('Testes da biblioteca lista_usuario\&.hpp:')"

.PP
Definition at line 12 of file Testes\&.cpp\&.
.SS "TEST_CASE ('Testes da biblioteca transacoes\&.hpp:')"

.PP
Definition at line 93 of file Testes\&.cpp\&.
.SS "TEST_CASE ('Testes da biblioteca categoria\&.hpp:')"

.PP
Definition at line 157 of file Testes\&.cpp\&.
.SS "TEST_CASE ('Testes da biblioteca bancodados\&.hpp:')"

.PP
Definition at line 220 of file Testes\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOCIAL NETWORK from the source code\&.
