.TH "Trabalho/src/transacoes.cpp" 3 "Fri Jun 30 2017" "Version 1.0" "SOCIAL NETWORK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trabalho/src/transacoes.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'transacoes\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "noListaTransacao * \fBcriaNoTransacao\fP (Transacao transacao)"
.br
.ti -1c
.RI "Servico \fBCriaServicoUsuario\fP (Usuario usuarioProvedor, char *precoServico, char *descricaoServico)"
.br
.ti -1c
.RI "Transacao \fBMontaTransacao\fP (Servico servicoUsuario, Categoria categoriaServico)"
.br
.ti -1c
.RI "ListaTransacao * \fBcriarListaTransacao\fP ()"
.br
.ti -1c
.RI "int \fBaddNoListaTransacaoExistente\fP (ListaTransacao *lista, noListaTransacao *no)"
.br
.ti -1c
.RI "int \fBaddNoListaTransacaoNova\fP (ListaTransacao *lista, noListaTransacao *no)"
.br
.ti -1c
.RI "int \fBdeletaNoListaTransacao\fP (ListaTransacao *lista, noListaTransacao *no)"
.br
.ti -1c
.RI "noListaTransacao * \fBencontraNoTransacao\fP (noListaTransacao *inicio, Transacao transacao)"
.br
.ti -1c
.RI "int \fBLiberaListaTransacao\fP (ListaTransacao *listaTransacao)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int addNoListaTransacaoExistente (ListaTransacao * lista, noListaTransacao * no)"
Adiciona uma transacao na lista de transacoes, se ja existir no BD 
.PP
Definition at line 53 of file transacoes\&.cpp\&.
.SS "int addNoListaTransacaoNova (ListaTransacao * lista, noListaTransacao * no)"
Adiciona uma transacao na lista de transacoes, se for nova 
.PP
Definition at line 80 of file transacoes\&.cpp\&.
.SS "noListaTransacao* criaNoTransacao (Transacao transacao)"
Funcao que cria o no de transacao Cria nó 
.PP
Definition at line 5 of file transacoes\&.cpp\&.
.SS "ListaTransacao* criarListaTransacao ()"
Cria lista 
.PP
Definition at line 41 of file transacoes\&.cpp\&.
.SS "Servico CriaServicoUsuario (Usuario usuarioProvedor, char * precoServico, char * descricaoServico)"
Funcao que monta o tipo servico do usuario que vai adicionar na transacao sendo criada Variavel do tipo servico para abrigar os atributos do servico que o usuario usuarioProvedor esta criando 
.PP
Definition at line 17 of file transacoes\&.cpp\&.
.SS "int deletaNoListaTransacao (ListaTransacao * lista, noListaTransacao * no)"
Deleta uma transacao da lista de transacoes pelo seu id Caso o nó esteja no meio da lista
.PP
Caso o nó esteja no fim da lista
.PP
Caso o nó seja o primeiro da lista 
.PP
Definition at line 111 of file transacoes\&.cpp\&.
.SS "noListaTransacao* encontraNoTransacao (noListaTransacao * inicio, Transacao transacao)"
Procura uma transacao na lista de transacoes Primeiro no da lista 
.PP
Definition at line 150 of file transacoes\&.cpp\&.
.SS "int LiberaListaTransacao (ListaTransacao * listaTransacao)"

.PP
Definition at line 173 of file transacoes\&.cpp\&.
.SS "Transacao MontaTransacao (Servico servicoUsuario, Categoria categoriaServico)"
Funcao que monta a transacao que vai ser adicionada, recebendo o servico e a categoria do servico 
.PP
Definition at line 29 of file transacoes\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SOCIAL NETWORK from the source code\&.
